name: CD
on:
  push:
    branches:
      - "master"
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: luccasbeltrame
          password: ${{ secrets.DOCKER_PASSWORDS }}
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: luccasbeltrame/go:${{github.sha}}

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: kustomize
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: v4.5.5
          kustomize_build_dir: 'k8s'

      - name: update k8s
        run: |
          kustomize edit set image goapp=luccasbeltrame/go:${{github.sha}}
          cat kustomization.yaml

      - name: commit
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"
      - name: push
        uses: ad-m/github-push-action@master 



       
